
/* This file was generated by idltool 53.35. Do not edit */

#include "ciab_vectors.h"

STATIC uint32 VARARGS68K _ciab_UNIMPLEMENTED(struct ciabIFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _ciab_Obtain,
    _ciab_Release,
    _ciab_UNIMPLEMENTED, /* Expunge */
    _ciab_UNIMPLEMENTED, /* Clone */
    _ciab_AddICRVector,
    _ciab_RemICRVector,
    _ciab_AbleICR,
    _ciab_SetICR,
    _ciab_NallePuh,
    (APTR)-1
};
