/*
**	$Id$
**	Generated by IDLTool 53.35
**	Do not edit
**
**	AutoInit stub for ciaa
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <exec/interrupts.h>
#include <exec/libraries.h>

#include <interfaces/ciaa.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

struct ciaaIFace * Iciaa = NULL;
static struct Library * __ciaaBase = NULL;
static struct ciaaIFace * __Iciaa = NULL;

/****************************************************************************/

extern struct Library * ciaaBase;

/****************************************************************************/

void _INIT_5_Iciaa(void)
{
    if (Iciaa != NULL)
    {
        return; /* Someone was quicker */
    }
    if (ciaaBase == NULL) /* Library base is NULL, we need to open it */
    {
        /* We were called before the base constructor.
         * This means we will be called _after_ the base destructor.
         * So we cant drop the interface _after_ closing the last library base,
         * we just open the library here which ensures that.
         */
        __ciaaBase = ciaaBase = IExec->OpenLibrary("ciaa.resource", 0);
        if (ciaaBase == NULL)
        {
            BPTR StdErr = IDOS->ErrorOutput();
            if (StdErr == ZERO)
                StdErr = IDOS->Output();
            IDOS->FPrintf(StdErr, "ERROR: Failed to open '%s'.\n", "ciaa.resource");
            abort();
        }
    }

    __Iciaa = Iciaa = (struct ciaaIFace *)IExec->GetInterface((struct Library *)ciaaBase, "main", 1, NULL);
    if (Iciaa == NULL)
    {
        BPTR StdErr = IDOS->ErrorOutput();
        if (StdErr == ZERO)
            StdErr = IDOS->Output();
        IDOS->FPrintf(StdErr, "ERROR: Failed to get '%s' V%ld interface for '%s'.\n", "main", 1, "ciaa.resource");
        abort();
    }
}
#ifdef __GNUC__
__attribute__((section(".ctors.zzzy"))) static void
(*ciaa_main_constructor_ptr)(void) USED = _INIT_5_Iciaa;
#endif

/****************************************************************************/

void _EXIT_5_Iciaa(void)
{
    if (__Iciaa)
    {
        IExec->DropInterface ((struct Interface *)__Iciaa);
    }
    if (__ciaaBase)
    {
        IExec->CloseLibrary(__ciaaBase);
    }
}
#ifdef __GNUC__
__attribute__((section(".dtors.zzzy"))) static void
(*ciaa_main_destructor_ptr)(void) USED = _EXIT_5_Iciaa;
#endif

/****************************************************************************/

