
/* This file was generated by idltool 53.35. Do not edit */

#include "ciaa_vectors.h"

STATIC uint32 VARARGS68K _ciaa_UNIMPLEMENTED(struct ciaaIFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _ciaa_Obtain,
    _ciaa_Release,
    _ciaa_UNIMPLEMENTED, /* Expunge */
    _ciaa_UNIMPLEMENTED, /* Clone */
    _ciaa_AddICRVector,
    _ciaa_RemICRVector,
    _ciaa_AbleICR,
    _ciaa_SetICR,
    _ciaa_NallePuh,
    (APTR)-1
};
