
/* This file was generated by idltool 53.35. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef EXEC_INTERRUPTS_H
#include <exec/interrupts.h>
#endif
#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

/* forward declaration */
struct ciaaIFace;

extern ULONG                VARARGS68K _ciaa_Obtain(struct ciaaIFace *);
extern ULONG                VARARGS68K _ciaa_Release(struct ciaaIFace *);
extern struct Interrupt *   VARARGS68K _ciaa_AddICRVector(struct ciaaIFace *, struct Library * resource, WORD iCRBit, struct Interrupt * interrupt);
extern VOID                 VARARGS68K _ciaa_RemICRVector(struct ciaaIFace *, struct Library * resource, WORD iCRBit, struct Interrupt * interrupt);
extern WORD                 VARARGS68K _ciaa_AbleICR(struct ciaaIFace *, struct Library * resource, WORD mask);
extern WORD                 VARARGS68K _ciaa_SetICR(struct ciaaIFace *, struct Library * resource, WORD mask);
extern struct Interupt **   VARARGS68K _ciaa_NallePuh(struct ciaaIFace *, ULONG state, APTR chip);
