#ifndef INLINE4_CIAA_H
#define INLINE4_CIAA_H

/*
** This file was auto generated by idltool 53.35.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_INTERRUPTS_H
#include <exec/interrupts.h>
#endif
#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif
#include <interfaces/ciaa.h>

/* Inline macros for Interface "main" */
#define AddICRVector(resource, iCRBit, interrupt) Iciaa->AddICRVector((resource), (iCRBit), (interrupt))
#define RemICRVector(resource, iCRBit, interrupt) Iciaa->RemICRVector((resource), (iCRBit), (interrupt))
#define AbleICR(resource, mask) Iciaa->AbleICR((resource), (mask))
#define SetICR(resource, mask) Iciaa->SetICR((resource), (mask))
#define NallePuh(state, chip) Iciaa->NallePuh((state), (chip))

#endif /* INLINE4_CIAA_H */
