/*
**	$Id$
**	Generated by IDLTool 53.35
**	Do not edit
**
**	AutoInit stub for ciab
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <exec/interrupts.h>
#include <exec/libraries.h>

#include <interfaces/ciab.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

/****************************************************************************/

struct Library * ciabBase = NULL;
static struct Library * __ciabBase = NULL;

/****************************************************************************/

void _INIT_5_ciabBase(void)
{
    if (ciabBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __ciabBase = ciabBase = IExec->OpenLibrary("ciab.resource", 0);
    if (ciabBase == NULL)
    {
        BPTR StdErr = IDOS->ErrorOutput();
        if (StdErr == ZERO)
            StdErr = IDOS->Output();
        IDOS->FPrintf(StdErr, "ERROR: Failed to open '%s'.\n", "ciab.resource");
        abort();
    }
}

#ifdef __GNUC__
__attribute__((section(".ctors.zzzz"))) static void
(*ciab_base_constructor_ptr)(void) USED = _INIT_5_ciabBase;
#endif

/****************************************************************************/

void _EXIT_5_ciabBase(void)
{
    if (__ciabBase != NULL)
    {
        IExec->CloseLibrary(__ciabBase);
    }
}

#ifdef __GNUC__
__attribute__((section(".dtors.zzzz"))) static void
(*ciab_base_destructor_ptr)(void) USED = _EXIT_5_ciabBase;
#endif

/****************************************************************************/

