
/* This file was generated by idltool 53.35. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef EXEC_INTERRUPTS_H
#include <exec/interrupts.h>
#endif
#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif

/* forward declaration */
struct ciabIFace;

extern ULONG                VARARGS68K _ciab_Obtain(struct ciabIFace *);
extern ULONG                VARARGS68K _ciab_Release(struct ciabIFace *);
extern struct Interrupt *   VARARGS68K _ciab_AddICRVector(struct ciabIFace *, struct Library * resource, WORD iCRBit, struct Interrupt * interrupt);
extern VOID                 VARARGS68K _ciab_RemICRVector(struct ciabIFace *, struct Library * resource, WORD iCRBit, struct Interrupt * interrupt);
extern WORD                 VARARGS68K _ciab_AbleICR(struct ciabIFace *, struct Library * resource, WORD mask);
extern WORD                 VARARGS68K _ciab_SetICR(struct ciabIFace *, struct Library * resource, WORD mask);
extern BOOL                 VARARGS68K _ciab_NallePuh(struct ciabIFace *, ULONG state, APTR chip);
